import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)
//
// Docusaurus treats EVERY named export of this file as a sidebar definition, so the
// lesson-regrouping generator lives in ./sidebarItemsGenerator.ts and is wired up from
// docusaurus.config.ts instead.

const sidebars: SidebarsConfig = {
  docSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;