# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # Cho phép chạy bằng tay từ giao diện Github
  workflow_dispatch:
  # Lên lịch chạy hàng ngày vào lúc 00:00 UTC
  schedule:
  - cron: "12 0 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: Ubuntu-20.04 

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.4.3
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      # Khởi tạo môi trường NodeJS
    - name: Generate quote
      # Chạy script để gọi API lấy quote sau đó sửa file README.md
      run: node index.js
      
    #- name: Update README.md
      # Push file README.md đã được thay đổi lên github
      #run: |
       # git config --global user.email "tranphanthanhlong18@gmail.com"
      #  git config --global user.name "TikTzuki"
       # git add .
       # git commit -m "Updated README.md" || echo "No changes to commit"
       # git push
