name: GitHub Page

on:
  push:
    branches: [ master ]
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

#      - name: Build project
#        run: |
#          npm ci
#          npm run build

      - name: Deploy to external repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          external_repository: TikTzuki/tiktzuki.githuub.io
          publish_dir: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages # or gh-pages
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com